- name: Update System
  apt:
    upgrade: dist
    update_cache: no

- name: Install Python 3
  apt:
    pkg:
      - python3
      - python3-pip
      - git
    state: present

- name: Install Pipenv
  pip:
    name: pipenv

- name: Directory Application
  file:
    path: "{{ app_directory }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Clone App
  git:
    repo: https://github.com/tiagopgeremias/minio-upload.git
    dest: "{{ app_directory }}"
    force: yes

- name: Setup App
  shell: "cd {{ app_directory }} && pipenv --python 3 install --system --deploy"

- name: Create .env
  template:
    src: env.j2
    dest: "{{app_directory}}/.env"
    owner: ubuntu
    group: ubuntu
    mode: '0644'

- name: Start App
  shell: "gunicorn --chdir {{app_directory}} --bind 0.0.0.0:5000 wsgi:app --daemon"