- name: Create data directory
  file:
    path: "{{ minio_data_directory }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Create Bucket
  file:
    path: "{{ minio_data_directory }}/files"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755
  register: bucket_dir


- name: Create minio directory
  file:
    path: "{{ minio_server_path }}"
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Download Server Min.io
  get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: "{{ minio_server_path }}/minio"
    mode: 0755
    owner: ubuntu
    group: ubuntu
    force: no

- name: Start Server Min.io
  shell: "{{ minio_server_path }}/minio server /mnt/data >/dev/null 2>&1 &"
  async: 10
  poll: 0
  # environment:
  #   MINIO_ACCESS_KEY: "{{ minio_access }}"
  #   MINIO_SECRET_KEY: "{{ minio_secret }}"
  #   S3_URL: "http://{{ inventory_hostname }}:9000"
  #   S3_ACCESS_KEY: "{{ minio_access }}"
  #   S3_SECRET_KEY: "{{ minio_secret }}"
